# configuration for https://rust-lang.github.io/rustfmt/
version = "Two"
newline_style = "Unix"
# comments
normalize_comments=true
wrap_comments=true
comment_width = 100
format_code_in_doc_comments = true
# imports 
imports_granularity="Crate"
group_imports="StdExternalCrate"
# ignore
ignore = [
    "examples",
]
# length
max_width = 80